on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  automate_report:
    name: 'Auto push a commit to my repo'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create sample file with just timestamp
      run: date +%s >> report.txt
    - name: Commit file
      run: |
          git pull
          git config --global user.name 'Automated Turtle 404'
          git config --global user.email '20079883+luanldt@users.noreply.github.com'
          git add report.txt
          git commit -am "Automated report"
          git push
          
  automate_image:
    needs: [automate_report]
    name: Download image and save into disk
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        uses: dcarbone/install-jq-action@v1.0.1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run script
        run: |
          sed -i -e 's/\r$//' ./scripts/execute.sh;
          chmod +x ./scripts/execute.sh;
          ./scripts/execute.sh '${{ secrets.IMAGE_SOURCE_URL }}' '${{ vars.JSON_FILE }}';
        shell: bash
      - name: Commit
        run: |
          git pull
          git config --global user.name 'Automated Turtle 404'
          git config --global user.email '20079883+luanldt@users.noreply.github.com'
          git add ${{ vars.JSON_FILE }}
          git commit -am "Automated submit"
          git push
