on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  automate_image:
    name: Download image and save into disk
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        uses: dcarbone/install-jq-action@v1.0.1
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run script
        run: |
          ls -la
          sed -i -e 's/\r$//' ./scripts/execute.sh
          chmod +x ./scripts/execute.sh
          ./scripts/execute.sh ${{ secrets.IMAGE_SOURCE_URL }} ${{ env.FILE_JSON }}
      - name: Commit
        run: |
          git config --global user.name 'Automated Turtle 404'
          git config --global user.email 'turtle.kiri@users.noreply.github.com'
          git add .
          git commit -am "Automated submit"
          git push
